Importing the issential libraries

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

Loading the tiatanic dataset

In [3]:
df = pd.read_csv('../data/titanic.csv')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

# About this Dataset

RMS Titanic was a British luxury ocean liner, renowned as one of the largest and most opulent ships of its era. Built by Harland & Wolff in Belfast, it measured about 883 feet long, 92 feet wide, and could carry over 3,500 passengers and crew
On April 10, 1912, Titanic departed Southampton for New York with 2,208 aboard. It struck an iceberg on April 14, sinking early on April 15 and claiming around 1,500 lives—one of history's deadliest peacetime maritime disasters

This data shows the limited amount of passengers which were there on, **Titanic** that day

### Column description

1. ```Survived``` :- It shows wether that passenger survived or not using *0 = No, 1 = Yes*
2. ```Pclass``` :- Ticket class	*1 = 1st;Upper, 2 = 2nd;Middle, 3 = 3rd;Lower*
3. ```Name``` :- Shows the name of the passenger 
4. ```Sex``` :-  Shows the gender of tha passenger
5. ```Age``` :- Shows the age of the passeger *Age is fractional if less than 1. If the age is estimated, is it in the form of xx.5*
6. ```SibSp``` :- The dataset defines family relations in this way 
; Sibling = brother, sister, stepbrother, stepsister
; Spouse = husband, wife *(mistresses and fiancés were ignored)*
7. ```Parch``` :- The dataset defines family relations in this way ;
Parent = mother, father ;
Child = daughter, son, stepdaughter, stepson ;
*Some children travelled only with a nanny, therefore parch=0 for them.*
8. ```Ticket``` :- Shows the ticket number of the passenger 
9. ```Fare``` :- Shows the fare of the passenger 
10. ```Cabin``` :- Shows the Cabin number of the passenger 
11. ```Embarked``` :- Port of Embarkation *C = Cherbourg, Q = Queenstown, S = Southampton*

#### Issues with the dataset

1. Dirty Data

- There are some missing values in ```Age``` column
- There are too many missing values in ```Cabin``` column
- very few values of ```Embarked``` are missing

2. Messy data

Thers no messy data as such

#### Define
- Filling missing values of columns ```Age``` and ```Embarked``` using mean() and mode() 
- Dropping column ```Cabin``` cause it has too many missing values

In [4]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [5]:
df = df.fillna({'Age': df['Age'].median()})

In [6]:
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])

In [7]:
df.drop(columns=['Cabin'], inplace=True)

In [8]:
df.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [36]:
df['lone_traveler'] = df['SibSp'] + df['Parch'] == 0

In [39]:
df['lone_traveler'] = df['lone_traveler'].replace({True: 'Yes', False: 'No'})

In [40]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,lone_traveler
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S,No
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,No
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S,Yes
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S,No
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S,Yes

In [41]:
df['family_size'] = df['SibSp'] + df['Parch'] + 1

In [43]:
df.head(18)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,lone_traveler,family_size
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S,No,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,No,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S,Yes,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S,No,2
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S,Yes,1
5,6,0,3,"Moran, Mr. James",male,28.0,0,0,330877,8.4583,Q,Yes,1
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,S,Yes,1
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,S,No,5
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,S,No,3
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,C,No,2
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,S,No,3
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,S,Yes,1
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,S,Yes,1
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,S,No,7
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,S,Yes,1
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,S,Yes,1
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,Q,No,6
17,18,1,2,"Williams, Mr. Charles Eugene",male,28.0,0,0,244373,13.0000,S,Yes,1

In [44]:
df= df.sort_values(by='Embarked', ascending=False)

In [45]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,lone_traveler,family_size
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S,No,2
554,555,1,3,"Ohman, Miss. Velin",female,22.0,0,0,347085,7.7750,S,Yes,1
540,541,1,1,"Crosby, Miss. Harriet R",female,36.0,0,2,WE/P 5735,71.0000,S,No,3
541,542,0,3,"Andersson, Miss. Ingeborg Constanzia",female,9.0,4,2,347082,31.2750,S,No,7
542,543,0,3,"Andersson, Miss. Sigrid Elisabeth",female,11.0,4,2,347082,31.2750,S,No,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...
97,98,1,1,"Greenfield, Mr. William Bertram",male,23.0,0,1,PC 17759,63.3583,C,No,2
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,C,Yes,1
255,256,1,3,"Touma, Mrs. Darwis (Hanne Youssef Razi)",female,29.0,0,2,2650,15.2458,C,No,3
762,763,1,3,"Barah, Mr. Hanna Assi",male,20.0,0,0,2663,7.2292,C,Yes,1
381,382,1,3,"Nakid, Miss. Maria (""Mary"")",female,1.0,0,2,2653,15.7417,C,No,3